baseURL = "https://recetas.domains.uflib.ufl.edu/"
defaultContentLanguage = "es"
title = "Trial Site"
theme = "MyTheme"
toc = true
paginate = 10000
sectionPagesMenu = "main"

[languages]
[languages.en]
title = "Recetas"
languageName = "English"
weight = 2

[languages.es]
title = "Recipes"
languageName = "Español"
weight = 1

[taxonomies]
ingredients = "ingredientes"
course = "plato"
tag = 'etiquettas'
[menu]

[[languages.es.menu.main2]]
name = 'Inicio'
url = '/'
weight = -110

[[languages.es.menu.main2]]
name = 'Recetas'
url = '/recetas'
weight = -100

[[languages.es.menu.main2]]
name = 'Acerca'
url = '/about'
weight = -100

[[languages.en.menu.main2]]
name = 'Home'
url = '/'
weight = -110

[[languages.en.menu.main2]]
name = 'About'
url = '/about'
weight = -100

[[languages.en.menu.main2]]
name = 'Recipes'
url = '/recetas'
weight = -100
